version: '3.3'

services:
  app:
    build: .
    image: ghcr.io/richmojo/amazon_stats:latest # Replace with your GitHub username, repository name, and preferred tag
    container_name: amazon_stats
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
